name: Update Major Tag

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update v1 tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -f v1
          # we use gh api to update the ref to avoid the tool restriction
          git_sha=$(git rev-parse HEAD)
          gh api \
            --method PATCH \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/git/refs/tags/v1 \
            -f sha="$git_sha" -f force=true
